spring:
  application:
    name: "loans"

  config:
    import: "optional:configserver:http://localhost:8071/"
  #provide connection details of rabbitmq inside each ms:
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

  datasource:
    url: jdbc:mysql://localhost:3306/loans_db
    username: root
    password: admin000pwd

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  profiles:
    active: qa

server:
  port: 9191

eureka:
  instance:
    preferIpAddress: true

  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka

management:
  endpoints:
    web:
      exposure:
        include: "health,info,refresh"

  endpoint:
    shutdown:
      enabled: true

  info:
    env:
      enabled: true

info:
  app:
    name: "loans"
    description: "Eazy banks loans application"
    version: "1.5"