spring:
  datasource:
    # MySQL is on host machine (NOT container)
    # Inside Docker we use host.docker.internal
    url: jdbc:mysql://host.docker.internal:3306/loans_db?useSSL=false&serverTimezone=UTC
    username: testingUser
    password: testing
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: never