package home.training.loans.entities;

import jakarta.persistence.*;
import lombok.*;

@Entity
@Getter @Setter @ToString @AllArgsConstructor @NoArgsConstructor
public class Loans extends BaseEntity {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long loanId; //id generated by the database

	private String mobileNumber;

	private String loanNumber;

	private String loanType; //student loan, house loan,

	private int totalLoan; //loan amount

	private int amountPaid; //quantity paid by customer

	private int outstandingAmount; //remaining amount.
	
}
